### ISSUE TITLE
SIMCOM 7600 AT Commands

### ISSUE THREAD

**Issue by DazFahy** [hbjorgo/ATLib#14]
Hi
    I have been developing a raspberry pi powered sensor. I am just adding the SIM7600G-H 4G HAT to the device. I started off using the standard serial ports but then came across your project and the implementation of pipes. I have taken a copy of the library and changed my code to run with the pipes. During the process I have added commands for the SIMCOM 7600 as well as some standard AT Commands. I have also added extra information to the SignalQuality including decibels. Also I am using UnitsNet for anything like decibels or voltages.

Is this something you would be interested in me providing a pull request for?

**Comment by hbjorgo** [comment]
Hi!
Awesome to hear this :) Support for more modems is appreciated.

I'd love a PR! But I need to see the implications of the unit library before I can decide if it should be included or not.
