### ISSUE TITLE
Stream WriteAsync Hang

### ISSUE THREAD

**Issue by ductai230894** [hbjorgo/ATLib#17]
Lib have a error hang Stream.Write async if COM can't write data, any way to fix it

this is code make problem
```
protected async Task WriteAsync(string text, CancellationToken cancellationToken = default)
        {
            
            Console.WriteLine($"write {text}");

            byte[] buffer = Encoding.UTF8.GetBytes(text);
            await stream.WriteAsync(buffer, 0, buffer.Length, cancellationToken); //hang, can't stop
            Console.WriteLine($"flush {text}");
            await stream.FlushAsync(cancellationToken);
            Console.WriteLine($"write {text} ok");

        }
```
I run in another Task, can't hang by UI, can you check it

**Comment by hbjorgo** [comment]
Thank you for reporting this! I'll have a look at it.

**Comment by ductai230894** [comment]
Thanks, wait for you

**Comment by hbjorgo** [comment]
If you use a SerialPort, you can set the [WriteTimeout property](https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport.writetimeout?view=dotnet-plat-ext-6.0) . You can set the number of milliseconds before it will throw a [TimeoutException](https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport.write?view=dotnet-plat-ext-6.0). Does it solve your problem?
