### ISSUE TITLE
How to make compatible with other brands

### ISSUE THREAD

**Issue by derodevil** [hbjorgo/ATLib#21]
I have Huawei and Wavecom M1306B. Do you have any idea how to set the library to make it work with those modems? Or you have generic custom settings to achieve that purpose?

**Comment by hbjorgo** [comment]
Hi!

You can try using one of the other implementations that are in the package. If it works, you're OK. All implementations use the same base class, and then they override the functions that differ from the generic one. The `Fona3G` implementation is equal to the generic one. If you can't find one that works for you, you could also create a PR if you're interested :)

If you positively test all the functions available against your modem, I can also add it to the library.
If there are some minor differences, you might be able to send me some sample responses and I can add it too.

**Comment by derodevil** [comment]
I have tried all but unfortunately failed. Well, I'll try to figure it out.
