### ISSUE TITLE
Record incomming call ????

### ISSUE THREAD

**Issue by ductai230894** [hbjorgo/ATLib#22]
Do you have plan add record incomming call function???
Or any idea to do it

**Comment by derodevil** [comment]
I think it's not related to this library. You can use another library to accomplish this task. There are many audio libraries in gihub you can use

**Comment by hbjorgo** [comment]
I don't know what modem you have, but I assume it has audio out through a minijack or similar. If so, you can use the appropriate hardware/software to capture this. If not, please feel free to open a new issue with more details.
