### ISSUE TITLE
UCS2 encoding schema for arabic sms messages

### ISSUE THREAD

**Issue by alialkaabi2007** [hbjorgo/ATLib#24]
Dear, I have Huawei e303 modem and i already able to use this library to send sms with this device, but now i have a problem sending Arabic language sms, i searched about it and found that it is a coding schema issue, i can send Arabic sms by another method but not with this library.
my device can support ("**GSM**", "**IRA**", "**UCS2**") character sets
so could you please explain for me how to implement the UCS2 coding schema for sending such type of sms using this library
thank you in advance.

**Comment by hbjorgo** [comment]
Hi!
Nice to hear that you're using the library 😀
I'll have a look at it and see if I can replicate it and take it from there.

**Comment by hbjorgo** [comment]
I've just released version 6.0.0. I've added support to select which encoding to use when sending SMS in PDU format. Please try out sending an SMS using this function: `modem.SendSmsInPduFormatAsync(phoneNumber, smsMessage, CodingScheme.UCS2)`. It supports a wider character set.
Please let me know if it solves your issue 🤞🏼

**Comment by abdoutech93** [comment]
@alialkaabi2007 which modem works for the Huawei e303 ?
