### ISSUE TITLE
International numbers

### ISSUE THREAD

**Issue by adamdudzik** [hbjorgo/ATLib#26]
What about 
Number = number.TrimStart('+');

In my case in Poland it doesn't work when plus is trimmed from phoneNumber.
It's ok when this line looks like this

Number = number;

BTW. it's great library, thanks for your work.

**Comment by hbjorgo** [comment]
Hi!

Thank you - it's so nice to hear that it's useful! :)

Poland has 9 digit numbers and the country code is 48 if I understand correctly. That means that for a national call/SMS you'd send it to `AAA AAA AAA`, and from other countries you'd send it to `+48 AAA AAA AAA` to reach a Polish number - correct?
Can you give me some examples of numbers that work and some that don't?

**Comment by adamdudzik** [comment]
Hi. Indeed +48 AAA AAA AAA - that's correct. 
I have a SIMCOM SIM7600G-H and it's compatible with SIM5320 so i've change

```
SmsTextFormat smsTextFormat = SmsTextFormat.Text;

atChannel.EnableDebug((string line) => Console.WriteLine(line));

using IModem modem = new SIM5320(atChannel);
```

I use TestConsole and enter the number +48 AAAAAAAAA to send sms.

With

`Number = number.TrimStart('+');` in PhoneNumbers.cs

- `**Out: AT+CMGS="48AAAAAAAAA"**
- In:
- In: >
- Out: test
- In:
- In:
- In: +CMS ERROR: 500
- SMS Reference: Error:`

With

`Number = number;`

- `Sending SMS...
- Out: AT+CMGS="+48AAAAAAAAA"
- In:
- In: >
- Out: test
- In:
- In:
- In: +CMGS: 179
- In:
- In: OK
- SMS Reference: Message Reference: 179`

If I use putty and a COM connection only format +48AAAAAAAAA or AAAAAAAAA is valid. The format 48AAAAAAAAAA is invalid.

**Comment by hbjorgo** [comment]
Version 6.0.1 is now out and contains the fix. Hope it fixes your issues. Thank you for reporting this and contributing to making this library better 👏🏼
