### ISSUE TITLE
Support for Multi-part PDU?

### ISSUE THREAD

**Issue by vflame** [hbjorgo/ATLib#30]
Is this supported? (concatenation of sms over 160 ch)

**Comment by hbjorgo** [comment]
Hi!

Thank you for your interest in the library 😀

I'll look into it!

**Comment by hbjorgo** [comment]
This is now added to the latest version [7.0.0-RC1](https://github.com/hbjorgo/ATLib/releases/tag/7.0.0-RC1)
I hope you find it useful 🤞🏼
