### ISSUE TITLE
Telit soft reset and set to factory profile feature request

### ISSUE THREAD

**Issue by turmalin** [hbjorgo/ATLib#33]
Hi, 
we are evaluating your library to communicate with Telit xe910 famiy GSM terminals.  Time to time we need to soft reset GSM terminal via ATZ and/or AT&Fxxx (Set To Factory Defined Configuration)  commands since terminal may hang and can't turn back to normal status due to several reasons.   I would be glad if Telit modules are added to supported modems and soft reset + set to factory defined configuration AT commands are added to supported AT commands
Kind Regards

**Comment by hbjorgo** [comment]
Hi!

Thank you for your interest in the library :)

I don't have any Telit modems at hand, so it's not that easy to add it and make sure it actually works. Could you link to a datasheet?

I have added three methods in version 7.0.0-RC3 which you can test:
`RestoreUserSettingsAsync`
`SaveUserSettingsAsync`
`ResetUserSettingsAsync`

Please let me know if this fulfills your needs, or if you would need something more, and we might be able to sort it out.

**Comment by turmalin** [comment]
Hi again,

First of all, thank you for your interest. You may use the link given below to access documentation about Telit xE910 family member ME910C1, including datasheet, product brief and AT command guide

https://www.telit.com/me910c1-download-zone/

Access to download zone resources may need login / registration process though.   I did not tested yet but, methods you added to library will fulfill my request of "soft reset" most probably.

Kind Regards

**Comment by turmalin** [comment]
Methods works as expected, thank you
