### ISSUE TITLE
How can I send SMS with delivery report?

### ISSUE THREAD

**Issue by minhdqtt** [hbjorgo/ATLib#36]
First, thank you for awesome lib.

My question is how can I send sms with the delivery report. Someone on internet said that we need to setup modem by send the 2 commands:
AT+CNMI=2,1,0,1,0
AT+CSMP=49,167,0,0

I tried, but not success.

**Comment by hbjorgo** [comment]
Thank you for the kind words 😃 

I looked into this and the only way to get the delivery report response is to use the debug mode. I've started looking into this, and I'll hopefully have a new version ready soon.

Thank you for the request!

**Comment by hbjorgo** [comment]
Release [8.0.0](https://github.com/hbjorgo/ATLib/releases/tag/8.0.0) is out.
When sending SMS, you can specify `EnableStatusReportRequest = true` in the `SmsSubmitRequest`.
