### ISSUE TITLE
Gsm7 Default encoding not reflecting LF/CR properly

### ISSUE THREAD

**Issue by vflame** [hbjorgo/ATLib#42]
The encoding table (Gsm7) is not correctly accounting for LF/CR  ( \n and \r ) and I suppose escape:

It should be:

```
{ Gsm7Extension.Default, "@£$¥èéùìòÇ\nØø\rÅåΔ_ΦΓΛΩΠΨΣΘΞ\x1bÆæßÉ !\"#¤%&'()*+,-./0123456789:;<=>?¡ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÑÜ§¿abcdefghijklmnopqrstuvwxyzäöñüà" },
```

https://github.com/hbjorgo/ATLib/pull/43

Thanks for the library!

**Comment by hbjorgo** [comment]
Thanks for the heads up and the PR.
This was fixed together with other fixes and is included in version 8.0.0.
