### ISSUE TITLE
Sms Receiving

### ISSUE THREAD

**Issue by RobManley** [hbjorgo/ATLib#44]
Good Morning
Thank you for the wonderful code. Must have taken you some time to write all that.

I really want to use your library however I need to be able to receive sms and parse.

Do you foresee this feature being available soon?

Thanks again for your hard work
Rob

**Comment by abdoutech93** [comment]
It's already available

**Comment by hbjorgo** [comment]
Thank you for your kind words!
The functionality is there, and with the new version 8.0.0 release, it's better than ever.
There is an example in the [readme](https://github.com/hbjorgo/ATLib/blob/main/README.md) - have a look at that. If you still have issues - feel free to get in touch again.
