### ISSUE TITLE
can I use smartphone bluetooth or usb as a modem instead of usb modem ? 

### ISSUE THREAD

**Issue by abdoutech93** [hbjorgo/ATLib#47]

**Comment by hbjorgo** [comment]
Could be - you can connect to any stream as long as the device supports AT commands over that stream.
But I doubt that any smart phone supports it. Perhaps in some debug mode.

**Comment by abdoutech93** [comment]
I see some applications works with at commands trough Bluetooth or usb ( smartphone, or old classic phone with Bluetooth)

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
