### ISSUE TITLE
I add packed HeboTech.ATLib into my project. But I could not install package 'HeboTech.ATLib 7.0.0'

### ISSUE THREAD

**Issue by hoainghia2403** [hbjorgo/ATLib#49]
NuGet\Install-Package : Could not install package 'HeboTech.ATLib 7.0.0'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that 
framework. For more information, contact the package author.
At line:1 char:1
+ NuGet\Install-Package HeboTech.ATLib -Version 7.0.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
    
    I was update new visual studio version 17.11.3, and i changed NETFramework,Version 4.8. It not working

**Comment by ravor-org** [comment]
The latest versions are supporting .NET Standard 2.1, which is not compatible with .NET Framework (no matter of version). See https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1 for further reference. If you want to use the library with .NET Framework, you have to use version 6 as it still supports .NET Standard 2.0. As per Microsoft .NET Standard 2.0 is fully supported in .NET Framework 4.7 and higher. If there's no real need for .NET Framework, you could also start over with .NET Core.

**Comment by hbjorgo** [comment]
That is correct. The library no longer supports .Net Framework.
