### ISSUE TITLE
How to access SMS message in Preview Version 8.0.0-beta

### ISSUE THREAD

**Issue by abdoutech93** [hbjorgo/ATLib#50]
Also in version 7.0.0-beta2 I'm getting an error Attribute Message not found in call Sms !!!

**Comment by hbjorgo** [comment]
Hi!
Did you figure it out, or could you please provide some more details?

**Comment by hbjorgo** [comment]
8.0.0-beta1 is out. Perhaps that fixes your issue?

**Comment by abdoutech93** [comment]
> 8.0.0-beta1 is out. Perhaps that fixes your issue?

I'll test it and see. I'll keep you updated.

**Comment by hbjorgo** [comment]
[8.0.0-beta2](https://github.com/hbjorgo/ATLib/releases/tag/8.0.0-beta2) is just out.

**Comment by hbjorgo** [comment]
Release [8.0.0](https://github.com/hbjorgo/ATLib/releases/tag/8.0.0) is out.
Have a look at the example in the [readme](https://github.com/hbjorgo/ATLib/blob/main/README.md).
I'll close this issue, but feel free to create a new one if you still have issues.
